// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CarrosselDocumentDataSlicesSlice = never;

/**
 * Content for Carrossel documents
 */
interface CarrosselDocumentData {
  /**
   * Name field in *Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Cliente field in *Carrossel*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.cliente
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cliente: prismic.ContentRelationshipField<"cliente">;

  /**
   * Slice Zone field in *Carrossel*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CarrosselDocumentDataSlicesSlice> /**
   * Meta Title field in *Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: carrossel.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: carrossel.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Carrossel document from Prismic
 *
 * - **API ID**: `carrossel`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CarrosselDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CarrosselDocumentData>,
    "carrossel",
    Lang
  >;

type CategoriaDocumentDataSlicesSlice = never;

/**
 * Content for Categoria documents
 */
interface CategoriaDocumentData {
  /**
   * Categoria field in *Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categoria.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  categoria: prismic.KeyTextField;

  /**
   * Cliente field in *Categoria*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: categoria.cliente
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cliente: prismic.ContentRelationshipField<"cliente">;

  /**
   * Slice Zone field in *Categoria*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: categoria.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CategoriaDocumentDataSlicesSlice> /**
   * Meta Title field in *Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: categoria.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: categoria.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Categoria*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categoria.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Categoria document from Prismic
 *
 * - **API ID**: `categoria`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoriaDocumentData>,
    "categoria",
    Lang
  >;

type ClienteDocumentDataSlicesSlice = never;

/**
 * Content for Cliente documents
 */
interface ClienteDocumentData {
  /**
   * Logo field in *Cliente*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cliente.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *Cliente*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cliente.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Slug field in *Cliente*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cliente.slug
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Role field in *Cliente*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cliente
   * - **API ID Path**: cliente.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  role: prismic.SelectField<"Cliente" | "Empresa" | "Admin", "filled">;

  /**
   * Billing field in *Cliente*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Ativo
   * - **API ID Path**: cliente.billing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  billing: prismic.SelectField<"Ativo" | "Inativo" | "Pendente", "filled">;

  /**
   * Empresa Responsável field in *Cliente*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cliente.empresa_responsavel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  empresa_responsavel: prismic.ContentRelationshipField<"empresa">;

  /**
   * Slice Zone field in *Cliente*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cliente.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClienteDocumentDataSlicesSlice> /**
   * Meta Title field in *Cliente*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: cliente.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Cliente*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: cliente.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Cliente*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cliente.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Cliente document from Prismic
 *
 * - **API ID**: `cliente`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClienteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClienteDocumentData>,
    "cliente",
    Lang
  >;

type ConfiguracoesDocumentDataSlicesSlice = never;

/**
 * Content for Configurações documents
 */
interface ConfiguracoesDocumentData {
  /**
   * Cliente field in *Configurações*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.cliente
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cliente: prismic.ContentRelationshipField<"cliente">;

  /**
   * Background Color Primary field in *Configurações*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.background_color_primary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color_primary: prismic.ColorField;

  /**
   * Background Color Secundary field in *Configurações*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.background_color_secundary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color_secundary: prismic.ColorField;

  /**
   * Button Color field in *Configurações*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.button_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_color: prismic.ColorField;

  /**
   * Button Label Color field in *Configurações*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.button_label_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_label_color: prismic.ColorField;

  /**
   * Button Color Hover field in *Configurações*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.button_color_hover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_color_hover: prismic.ColorField;

  /**
   * Button Label Color Hover field in *Configurações*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.button_label_color_hover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_label_color_hover: prismic.ColorField;

  /**
   * Border Radius field in *Configurações*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: .05
   * - **API ID Path**: configuracoes.border_radius
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  border_radius: prismic.SelectField<".05" | ".03" | "1", "filled">;

  /**
   * Marketing field in *Configurações*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: configuracoes.marketing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  marketing: prismic.BooleanField;

  /**
   * Slice Zone field in *Configurações*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ConfiguracoesDocumentDataSlicesSlice> /**
   * Meta Title field in *Configurações*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: configuracoes.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Configurações*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: configuracoes.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Configurações*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracoes.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Configurações document from Prismic
 *
 * - **API ID**: `configuracoes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfiguracoesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ConfiguracoesDocumentData>,
    "configuracoes",
    Lang
  >;

type EmpresaDocumentDataSlicesSlice = never;

/**
 * Content for Empresa documents
 */
interface EmpresaDocumentData {
  /**
   * Logo field in *Empresa*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Business Name field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.BusinessName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  BusinessName: prismic.KeyTextField;

  /**
   * Slug field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.slug
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Billing field in *Empresa*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Ativo
   * - **API ID Path**: empresa.billing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  billing: prismic.SelectField<"Ativo" | "Inativo" | "Pendente", "filled">;

  /**
   * Rule field in *Empresa*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Empresa
   * - **API ID Path**: empresa.rule
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  rule: prismic.SelectField<"Empresa" | "Cliente" | "Admin", "filled">;

  /**
   * CNPJ field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.cnpj
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cnpj: prismic.KeyTextField;

  /**
   * Email field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * WhatsApp field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.whatsapp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  whatsapp: prismic.KeyTextField;

  /**
   * Slice Zone field in *Empresa*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EmpresaDocumentDataSlicesSlice> /**
   * Meta Title field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: empresa.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Empresa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: empresa.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Empresa*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: empresa.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Empresa document from Prismic
 *
 * - **API ID**: `empresa`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EmpresaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EmpresaDocumentData>,
    "empresa",
    Lang
  >;

type LinkDocumentDataSlicesSlice = never;

/**
 * Content for Link documents
 */
interface LinkDocumentData {
  /**
   * Logo field in *Link*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: link.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Categoria field in *Link*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: link.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  categoria: prismic.ContentRelationshipField<"categoria">;

  /**
   * Cliente field in *Link*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: link.cliente
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cliente: prismic.ContentRelationshipField<"cliente">;

  /**
   * Label field in *Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * URL field in *Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Background Color field in *Link*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: link.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Background Color Hover field in *Link*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: link.background_color_hover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color_hover: prismic.ColorField;

  /**
   * Label Color field in *Link*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: link.label_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  label_color: prismic.ColorField;

  /**
   * Label Color Hover field in *Link*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: link.label_color_hover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  label_color_hover: prismic.ColorField;

  /**
   * Border Radius field in *Link*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: link.border_radius
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  border_radius: prismic.SelectField<".03" | ".05" | "1">;

  /**
   * Slice Zone field in *Link*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: link.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LinkDocumentDataSlicesSlice> /**
   * Meta Title field in *Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: link.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: link.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Link*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: link.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Link document from Prismic
 *
 * - **API ID**: `link`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LinkDocumentData>, "link", Lang>;

type MidiaCarrosselDocumentDataSlicesSlice = never;

/**
 * Content for Midia Carrossel documents
 */
interface MidiaCarrosselDocumentData {
  /**
   * Cliente field in *Midia Carrossel*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.cliente
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cliente: prismic.ContentRelationshipField<"cliente">;

  /**
   * Carrossel field in *Midia Carrossel*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.carrossel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  carrossel: prismic.ContentRelationshipField<"carrossel">;

  /**
   * Imagem field in *Midia Carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Title field in *Midia Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Midia Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Price field in *Midia Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * Button Label field in *Midia Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button URL field in *Midia Carrossel*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.button_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_url: prismic.LinkField;

  /**
   * Slice Zone field in *Midia Carrossel*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MidiaCarrosselDocumentDataSlicesSlice> /**
   * Meta Title field in *Midia Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: midia_carrossel.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Midia Carrossel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: midia_carrossel.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Midia Carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: midia_carrossel.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Midia Carrossel document from Prismic
 *
 * - **API ID**: `midia_carrossel`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MidiaCarrosselDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MidiaCarrosselDocumentData>,
    "midia_carrossel",
    Lang
  >;

export type AllDocumentTypes =
  | CarrosselDocument
  | CategoriaDocument
  | ClienteDocument
  | ConfiguracoesDocument
  | EmpresaDocument
  | LinkDocument
  | MidiaCarrosselDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CarrosselDocument,
      CarrosselDocumentData,
      CarrosselDocumentDataSlicesSlice,
      CategoriaDocument,
      CategoriaDocumentData,
      CategoriaDocumentDataSlicesSlice,
      ClienteDocument,
      ClienteDocumentData,
      ClienteDocumentDataSlicesSlice,
      ConfiguracoesDocument,
      ConfiguracoesDocumentData,
      ConfiguracoesDocumentDataSlicesSlice,
      EmpresaDocument,
      EmpresaDocumentData,
      EmpresaDocumentDataSlicesSlice,
      LinkDocument,
      LinkDocumentData,
      LinkDocumentDataSlicesSlice,
      MidiaCarrosselDocument,
      MidiaCarrosselDocumentData,
      MidiaCarrosselDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
